version: '3'
services:
  python:
#    image: python:3.4
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    volumes: 
      - ./app:/app
    ports:
      - 8000:8000
#    command: sleep infinity
   # command: cd /app && pip install -r requirements.txt && python manage.py runserver 
